export const LOAD_ALHAMBRA = 'LOAD_ALHAMBRA';
export const LOAD_ALHAMBRA_START = 'LOAD_ALHAMBRA_START';
export const LOAD_ALHAMBRA_SUCCESS = 'LOAD_ALHAMBRA_SUCCESS';
export const LOAD_ALHAMBRA_ERROR = 'LOAD_ALHAMBRA_ERROR';

export const LOAD_BODYMOVIN = 'LOAD_BODYMOVIN';
export const LOAD_BODYMOVIN_START = 'LOAD_BODYMOVIN_START';
export const LOAD_BODYMOVIN_SUCCESS = 'LOAD_BODYMOVIN_SUCCESS';
export const LOAD_BODYMOVIN_ERROR = 'LOAD_BODYMOVIN_ERROR';

export const LOAD_SEQUENCE = 'LOAD_SEQUENCE';
export const LOAD_SEQUENCE_START = 'LOAD_SEQUENCE_START';
export const LOAD_SEQUENCE_SUCCESS = 'LOAD_SEQUENCE_SUCCESS';
export const LOAD_SEQUENCE_ERROR = 'LOAD_SEQUENCE_ERROR';

export const TOUR_LOCATION_CHANGED = 'TOUR_LOCATION_CHANGED';
export const TOUR_SPEAKING_CHANGED = 'TOUR_SPEAKING_CHANGED';
export const TOUR_SPEAKING_PLAYING = 'TOUR_SPEAKING_PLAYING';
export const TOUR_SPEAKING_PLAYBACK = 'TOUR_SPEAKING_PLAYBACK';
export const TOUR_DOMINANT_PLAYBACK = 'TOUR_DOMINANT_PLAYBACK';
export const TOUR_BEARING_CHANGED = 'TOUR_BEARING_CHANGED';
